#!/bin/bash

if [ "$1" == "new" ]
then
	WORKINGDIR=/home/sol1004/DVD-Creator2
else
	WORKINGDIR=/home/sol1004/DVD-Creator2/Update-CD
fi
cd $WORKINGDIR

for builddir in /builds/*
do
	# Set the name of the iso files
	isoname=$(basename $builddir)

	# Remove the current directory details and copy in new ones
	if [ "$1" == "new" ]
	then
		cd $WORKINGDIR/DVD/home/sol1004
	else
		cd $WORKINGDIR
	fi
	rm -rf conf tracks playlists
	cp -r $builddir/* .
	cd $WORKINGDIR

	if [ "$1" == "new" ]
	then
		if [ ! -e $builddir/cli-options.txt ]
		then
			echo "ERROR: No options file for $builddir"
			echo "Skipping this configuration"
			continue
		else
			. $builddir/cli-options.txt
			# File format;
			# net=dhcp
			# sound=Intel
			# tzname=Europe/London
		fi

		# if NSfile exists then read in contents to set variables for network
		if [ -e $builddir/NSfile ]
		then
			# File format is;
			# IP=192.168.11.1
			# NM=255.255.255.0
			# GW=192.168.11.254
			# NS=192.168.11.254
			. $builddir/NSfile
		fi

		# Build the ISOs
		./build-sollin-dvd $net $sound $isoname $tzname

		# unset the NSfile variables
		unset IP NM GW NS net sound tzname isoname
	else
		# Build update DVD
		OUTPUTDIR=$HOME/ISOs
		BUILDDIR=$WORKINGDIR
		cd $BUILDDIR
		mkisofs -o $OUTPUTDIR/${isoname}-update.iso -joliet-long -J -R -V "Sollin Update Disk" .
		unset isoname
	fi
done
